# Generated by Django 2.2.1 on 2019-11-22 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('edad', models.IntegerField(default=0)),
                ('sexo', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=200)),
                ('carrera', models.CharField(max_length=100)),
            ],
        ),
    ]
